In [4]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.identity(n)
    U = A.copy()
    
    print("Matriz inicial A:")
    print(A)
    print("\nInicializamos L como la matriz identidad y U como una copia de A.")
    print("L inicial:")
    print(L)
    print("U inicial:")
    print(U)
    print("\n")

    for k in range(n - 1):
        print(f"--- Iteración {k+1}: Trabajando en la columna {k+1} ---")
        
        for i in range(k + 1, n):
            # Calcula el factor multiplicativo
            f_ik = U[i, k] / U[k, k]
            print(f"\nEliminando elemento U[{i},{k}] usando la fila {k}")
            print(f"Factor multiplicativo f_{i}{k} = U[{i},{k}] / U[{k},{k}] = {f_ik}")
            
            # Guarda el factor en L
            L[i, k] = f_ik
            print(f"Actualizamos L[{i},{k}] = {f_ik}")
            print("L ahora es:")
            print(L)
            
            # Actualiza U restando el factor multiplicativo por la fila k
            U[i, k:] = U[i, k:] - f_ik * U[k, k:]
            print(f"Restamos {f_ik} veces la fila {k} de la fila {i} en U")
            print("U ahora es:")
            print(U)
            print("\n")
    
    print("--- Factorización completa ---")
    print("Matriz L final:")
    print(L)
    print("Matriz U final:")
    print(U)
    
    return L, U

# Ejemplo de uso
A = np.array([[2, 3, 1], 
              [4, 7, 2],
              [6, 18, 5]
              ], dtype=float)

L, U = lu_decomposition(A)


Matriz inicial A:
[[ 2.  3.  1.]
 [ 4.  7.  2.]
 [ 6. 18.  5.]]

Inicializamos L como la matriz identidad y U como una copia de A.
L inicial:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
U inicial:
[[ 2.  3.  1.]
 [ 4.  7.  2.]
 [ 6. 18.  5.]]


--- Iteración 1: Trabajando en la columna 1 ---

Eliminando elemento U[1,0] usando la fila 0
Factor multiplicativo f_10 = U[1,0] / U[0,0] = 2.0
Actualizamos L[1,0] = 2.0
L ahora es:
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]
Restamos 2.0 veces la fila 0 de la fila 1 en U
U ahora es:
[[ 2.  3.  1.]
 [ 0.  1.  0.]
 [ 6. 18.  5.]]



Eliminando elemento U[2,0] usando la fila 0
Factor multiplicativo f_20 = U[2,0] / U[0,0] = 3.0
Actualizamos L[2,0] = 3.0
L ahora es:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 0. 1.]]
Restamos 3.0 veces la fila 0 de la fila 2 en U
U ahora es:
[[2. 3. 1.]
 [0. 1. 0.]
 [0. 9. 2.]]


--- Iteración 2: Trabajando en la columna 2 ---

Eliminando elemento U[2,1] usando la fila 1
Factor multiplicativo f_21 = U[2,1] / U[1,1] = 9.0
Actualizamos L[2,1] = 9