
1. Sea
$$
A=\left(\begin{array}{ccc}
0 & -20 & 14 \\
-3 & 27 & 4 \\
-4 & 11 & 2
\end{array}\right)
$$
Implemente los métodos de ortogonalización de Gram-Schmindt y Householder, para calcular $A=Q R$, compare los resultados numéricos con los encontrados en las partes (a) y (b).

In [ ]:
import numpy as np

def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for i in range(n):
        v = A[:, i]
        for j in range(i):
            R[j, i] = np.dot(Q[:, j], A[:, i])
            v = v - R[j, i] * Q[:, j]
        R[i, i] = np.linalg.norm(v)
        Q[:, i] = v / R[i, i]

    return Q, R

def householder(A):
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()

    for i in range(n):
        x = R[i:, i]
        e1 = np.zeros_like(x)
        e1[0] = np.linalg.norm(x)
        v = x + e1
        v = v / np.linalg.norm(v)

        H = np.eye(m)
        H[i:, i:] -= 2.0 * np.outer(v, v)

        R = H @ R
        Q = Q @ H.T

    return Q, R

# Ejemplo de uso
A = np.array([[0,-20,14],[-3,27,4],[-4,11,2]], dtype=float)

Q_gs, R_gs = gram_schmidt(A)
Q_hh, R_hh = householder(A)

print("Gram-Schmidt:")
print("Q:\n", Q_gs)
print("R:\n", R_gs)
print("Householder:")
print("Q:\n", Q_hh)
print("R:\n", R_hh)


Gram-Schmidt:
Q:
 [[ 0.   -0.8   0.6 ]
 [-0.6   0.48  0.64]
 [-0.8  -0.36 -0.48]]
R:
 [[  5. -25.  -4.]
 [  0.  25. -10.]
 [  0.   0.  10.]]
Householder:
Q:
 [[ 2.22044605e-16  8.00000000e-01 -6.00000000e-01]
 [ 6.00000000e-01 -4.80000000e-01 -6.40000000e-01]
 [ 8.00000000e-01  3.60000000e-01  4.80000000e-01]]
R:
 [[-5.00000000e+00  2.50000000e+01  4.00000000e+00]
 [ 0.00000000e+00 -2.50000000e+01  1.00000000e+01]
 [ 0.00000000e+00 -5.99520433e-15 -1.00000000e+01]]



2. Descargue el archivo *Datos.txt* de la página del curso. En este encontrará un conjunto de 21 datos. Copie estos datos y calcule el polinomio de ajuste de grado $5 p(x)=c_{0}+c_{1} x+c_{2} x^{2}+c_{3} x^{3}+c_{4} x^{4}+c_{5} x^{5}$ utilizando los métodos de ecuaciones normales y factorización QR. Compare sus resultados con los valores certificados $c_{i}=1$ para $i=0,1, \ldots 5$. Encuentre el residual $\|A c-y\|_{2}$ en cada caso, así como la diferencia relativa con respecto a los valores certificados. Escriba sus conclusiones.

In [ ]:
import numpy as np
import scipy.linalg as la

x = np.arange(21)
y = np.array([75901, -204794, 204863, -204436, 253665, -200894, 214131, -185192, 221249, -138370,
              315911, -27644, 455253, 197434, 783995, 608816, 1370781, 1303798, 2205519, 2408860, 3444321])

A = np.vander(x, 6)

# Ecuaciones normales
ATA = A.T @ A
ATy = A.T @ y
c_normal = np.linalg.solve(ATA, ATy)

# QR
Q, R = la.qr(A, mode='economic')
y_tilde = Q.T @ y
c_qr = la.solve(R, y_tilde)

# Valores certificados
c_true = np.ones(6)

# Error residual ||Ac - y||_2
residual_normal = np.linalg.norm(A @ c_normal - y, 2)
residual_qr = np.linalg.norm(A @ c_qr - y, 2)

# Diferencia relativa con los valores certificados
diff_normal = np.linalg.norm(c_normal - c_true, 2) / np.linalg.norm(c_true, 2)
diff_qr = np.linalg.norm(c_qr - c_true, 2) / np.linalg.norm(c_true, 2)

print("Coeficientes usando ecuaciones normales:", c_normal)
print("Coeficientes usando factorización QR:", c_qr)
print("Residual (norma 2) - Ecuaciones normales:", residual_normal)
print("Residual (norma 2) - Factorización QR:", residual_qr)
print("Diferencia relativa - Ecuaciones normales:", diff_normal)
print("Diferencia relativa - Factorización QR:", diff_qr)


Coeficientes usando ecuaciones normales: [1.         1.         1.00000001 0.99999991 1.00000026 0.99999987]
Coeficientes usando factorización QR: [1. 1. 1. 1. 1. 1.]
Residual (norma 2) - Ecuaciones normales: 914080.2371783344
Residual (norma 2) - Factorización QR: 914080.2371783344
Diferencia relativa - Ecuaciones normales: 1.2672898828311217e-07
Diferencia relativa - Factorización QR: 1.0745195538266868e-09


5. Considere el sistema $A x=b$ donde
$$
A:=\left(\begin{array}{ccccc}
3 & -1 & -1 & 0 & 0 \\
-1 & 4 & 0 & -2 & 0 \\
-1 & 0 & 3 & -1 & 0 \\
0 & -2 & -1 & 5 & -1 \\
0 & 0 & 0 & -1 & 2
\end{array}\right) \quad b=\left(\begin{array}{c}
2 \\
-26 \\
3 \\
47 \\
-10
\end{array}\right)
$$

In [ ]:
import numpy as np

A = np.array([[3, -1, -1,  0,  0],
              [-1, 4,  0, -2,  0],
              [-1,  0,  3, -1,  0],
              [0, -2, -1,  5, -1],
              [0,  0,  0, -1,  2]])

b = np.array([2, -26, 3, 47, -10])

D = np.diag(np.diag(A))
L = -np.tril(A, -1)
U = -np.triu(A, 1)

T_J = np.linalg.inv(D) @ (L + U)  # Matriz de Jacobi
T_GS = np.linalg.inv(D - L) @ U    # Matriz de Gauss-Seidel

rho_J = max(abs(np.linalg.eigvals(T_J)))
rho_GS = max(abs(np.linalg.eigvals(T_GS)))

w = 2 / (1 + np.sqrt(1 - rho_GS**2)) # Omega óptimo para SOR

T_SOR = np.linalg.inv(D - w*L) @ ((1-w)*D + w*U)

rho_SOR = max(abs(np.linalg.eigvals(T_SOR)))

factor_reduccion = 1 - np.log(rho_GS)/np.log(rho_SOR)
delta_k_GS = np.log(0.1) / np.log(rho_GS)
delta_k_SOR = np.log(0.1) / np.log(rho_SOR)

print(f"Radio espectral de Jacobi: {rho_J:.2f}")
print(f"Radio espectral de Gauss Seidel: {rho_GS:.2f}")
print(f"Parámetro óptimo de sobrerelajación: {w:.2f}")
print(f"Radio espectral de SOR: {rho_SOR:.2f}")
print(f"SOR reduce el número de operaciones de Gauss Seidel en un {factor_reduccion*100:.2f}%")
print(f"Se necesitan {delta_k_GS:.2f} iteraciones para mejorar la precisión de Gauss Seidel en una cifra decimal")
print(f"Se necesitan {delta_k_SOR:.2f} iteraciones para mejorar la precisión de SOR en una cifra decimal")

Radio espectral de Jacobi: 0.72
Radio espectral de Gauss Seidel: 0.51
Parámetro óptimo de sobrerelajación: 1.08
Radio espectral de SOR: 0.43
SOR reduce el número de operaciones de Gauss Seidel en un 21.26%
Se necesitan 3.44 iteraciones para mejorar la precisión de Gauss Seidel en una cifra decimal
Se necesitan 2.71 iteraciones para mejorar la precisión de SOR en una cifra decimal


In [ ]:
np.log(0.1) / np.log(0.51)

3.4196238490876545